name: Deploy Unreleased Commits Generator

# Triggered manually via the "Run workflow" button
on:
  # Additional trigger to ensure this is updated after crawl
  schedule:
    - cron: 20 0 * * *
  # Runs on pushes to the default branch
  push:
    branches: ["main"]
  # Manual trigger
  workflow_dispatch:

permissions:
  contents: read  # Required to clone the repository
  pages: write    # Allows publishing to GitHub Pages
  id-token: write # Required for the `actions/deploy-pages@v4`

concurrency:
  group: generate
  cancel-in-progress: false

jobs:
  build:
    runs-on: arc-runner-set

    steps:
      # Step 1: Checkout the current repository into 'self' folder
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          path: self
          # Ensures full history is fetched for commit
          fetch-depth: 0

      # Step 2: Checkout the unreleasedcommits repository into 'unreleasedcommits' folder
      - name: Checkout unreleasedcommits repository
        uses: actions/checkout@v3
        with:
          repository: UnitVectorY-Labs/unreleasedcommits
          path: unreleasedcommits
          # Optionally, specify a branch if not default
          # ref: main

      # Step 3: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.3' # GOVERSION

      # Step 4: Build the unreleasedcommits binary
      - name: Build unreleasedcommits
        run: |
          cd unreleasedcommits
          go build -o unreleasedcommits .

      # Step 6: Run unreleasedcommits to scan and update the data folder
      - name: Run unreleasedcommits
        run: |
          cd ./self
          mkdir templates
          cp ../unreleasedcommits/templates/* ./templates/
          cp ../unreleasedcommits/unreleasedcommits ./unreleasedcommits
          ./unreleasedcommits --generate
        # Replace 'YOUR_ORG_NAME' with your actual GitHub organization name

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./self/output  # Match the directory where the static files are generated

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: gcp-iam-catalog.unitvectorylabs.com
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
